import Head from "next/head"
import NavBar from "../components/NavBar/NavBar"
import Profile from "../components/Profile/Profile"

export default function Home() {
  return (
    <>
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Profile />
      </main>
    </>
  )
}
