import { useState } from "react"

import Head from "next/head"
import NavBar from "../components/NavBar/NavBar"
import Profile from "../components/Profile/Profile"
import Content from "../components/Content/Content"

import projectsData from "./api/data.json"

export type ProjectData = {
  id: number
  name: string
  image: string[]
  description: string
  link: string
  codeLink: string
  technologies: string[]
  status: {
    views: string
    increaseViews: string
    likes: string
    increaseLikes: string
    decreaseLikes: string
  }
}[]

export default function Home() {
  const [data, setData] = useState(projectsData)
  const [sendMail, setSendMail] = useState(false)
  return (
    <>
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <NavBar />
          <Profile />
          <Content data={data} />
        </div>
      </main>
    </>
  )
}
